### ISSUE TITLE
Update for Firebase 2

### ISSUE THREAD

**Issue by nielsonrolim** [seanhess/ios-firebase-objects#1]
Hi,

This repository is outdated. It isn't working with Firebase 2.

I did an update, so it is now working fine with Firebase 2.

Could you add me as contributor so I could push and make a pull request to the master branch?

**Comment by seanhess** [comment]
You can make a pull request without being a contributor. Just fork the repository, and push your changes to your fork. Then go to your fork on github.com and there will be a pull request button. 

See here for details: https://help.github.com/articles/using-pull-requests/

Thanks for updating it!

**Comment by hsavit1** [comment]
hey did u ever get that to work?

**Comment by nielsonrolim** [comment]
No, we decided to use a webservice to get the information from the firebase database to the iOS app.

##
